# Generated by Django 3.2.7 on 2021-11-10 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211110_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='pf_projs',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pf_projs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
