# Generated by Django 3.2.7 on 2021-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211110_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pf_projs',
            name='body',
        ),
        migrations.AlterField(
            model_name='pf_projs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
