# Generated by Django 3.2.7 on 2021-11-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211110_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pf_projs',
            name='date_creation',
        ),
    ]
