# Generated by Django 3.2.7 on 2021-11-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pf_projs_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pf_projs',
            name='author',
        ),
    ]
