# Generated by Django 4.0.1 on 2022-01-11 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20211110_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pf_projs',
            new_name='pf_proj',
        ),
    ]
